// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkWKhQ9dmPTPMBsFCULo1zLtFmqkLw3yU',
    appId: '1:649312396208:web:0c4dd7a4d3d6c76e5b2c75',
    messagingSenderId: '649312396208',
    projectId: 'yandu-ad77b',
    authDomain: 'yandu-ad77b.firebaseapp.com',
    databaseURL: 'https://yandu-ad77b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yandu-ad77b.firebasestorage.app',
    measurementId: 'G-LBDM18PWQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2cYrghIoMmFZ86IFCyTd6_DesLSeu_Mw',
    appId: '1:649312396208:android:bcaedae0d0ed35d15b2c75',
    messagingSenderId: '649312396208',
    projectId: 'yandu-ad77b',
    databaseURL: 'https://yandu-ad77b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yandu-ad77b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtKm7gWD6lRHxEt5CdK-zAaDsKQQ0t7_Q',
    appId: '1:649312396208:ios:ef84870e7fa314d05b2c75',
    messagingSenderId: '649312396208',
    projectId: 'yandu-ad77b',
    databaseURL: 'https://yandu-ad77b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yandu-ad77b.firebasestorage.app',
    iosClientId: '649312396208-o219ha5gbhmgqgrftg675osijbv3c2hi.apps.googleusercontent.com',
    iosBundleId: 'com.example.yandu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtKm7gWD6lRHxEt5CdK-zAaDsKQQ0t7_Q',
    appId: '1:649312396208:ios:ef84870e7fa314d05b2c75',
    messagingSenderId: '649312396208',
    projectId: 'yandu-ad77b',
    databaseURL: 'https://yandu-ad77b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yandu-ad77b.firebasestorage.app',
    iosClientId: '649312396208-o219ha5gbhmgqgrftg675osijbv3c2hi.apps.googleusercontent.com',
    iosBundleId: 'com.example.yandu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkWKhQ9dmPTPMBsFCULo1zLtFmqkLw3yU',
    appId: '1:649312396208:web:291a3ef7f5272f445b2c75',
    messagingSenderId: '649312396208',
    projectId: 'yandu-ad77b',
    authDomain: 'yandu-ad77b.firebaseapp.com',
    databaseURL: 'https://yandu-ad77b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yandu-ad77b.firebasestorage.app',
    measurementId: 'G-WCC0SF9R42',
  );
}
